import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 📈 Stock Market Machine Learning Analysis & Prediction Notebook\n",
            "\n",
            "Welcome to the **Machine Learning Stock Analysis & Prediction Platform** in Jupyter Notebook.\n",
            "\n",
            "### 🎯 Project Objectives:\n",
            "1. **Data Acquisition**: Fetch real historical stock price data (e.g. `AAPL`, `NVDA`, `TSLA`, `MSFT`, `SPY`) via `yfinance` with realistic market generator fallback.\n",
            "2. **Technical Feature Engineering**: Compute 18 quantitative predictors including Moving Averages (SMA, EMA), Momentum & Oscillators (RSI, MACD, Stochastic, ROC), Volatility (Bollinger Bands, ATR), and Volume Dynamics (OBV).\n",
            "3. **Multi-Model ML Training**: Train and compare **Random Forest**, **Gradient Boosting**, **Ridge Regression**, **Multi-Layer Perceptron (MLP Neural Net)**, and an **Ensemble Predictor**.\n",
            "4. **Evaluation Metrics**: Evaluate RMSE, MAE, R² Score, and **Directional Accuracy (%)**.\n",
            "5. **Feature Importance Ranking**: Identify key technical drivers of price movement.\n",
            "6. **Algorithmic Trading Backtest**: Simulate portfolio execution, computing Cumulative ROI, Sharpe Ratio, Max Drawdown %, and Win Rate.\n",
            "7. **Multi-Day Forecasting**: Predict 1-day to 30-day future price paths with 90% confidence bounds."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Step 1: Import Required Libraries\n",
            "import os\n",
            "import datetime\n",
            "import warnings\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import yfinance as yf\n",
            "\n",
            "from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\n",
            "from sklearn.linear_model import Ridge\n",
            "from sklearn.neural_network import MLPRegressor\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\n",
            "\n",
            "# Styling setup\n",
            "plt.style.use('dark_background')\n",
            "sns.set_palette('muted')\n",
            "warnings.filterwarnings('ignore')\n",
            "print('✅ All quantitative machine learning packages imported successfully!')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## 📥 Step 2: Data Acquisition & Preprocessing"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def fetch_stock_dataset(symbol=\"AAPL\", period=\"2y\"):\n",
            "    \"\"\"\n",
            "    Fetches market data via yfinance with synthetic generator fallback.\n",
            "    \"\"\"\n",
            "    symbol = symbol.upper().strip()\n",
            "    print(f\"Downloading market data for {symbol} (period={period})...\")\n",
            "    try:\n",
            "        ticker = yf.Ticker(symbol)\n",
            "        df = ticker.history(period=period, interval=\"1d\")\n",
            "        if df.empty or len(df) < 30:\n",
            "            raise ValueError(\"Empty dataset received.\")\n",
            "        df = df.reset_index()\n",
            "        if \"Date\" not in df.columns and \"Datetime\" in df.columns:\n",
            "            df.rename(columns={\"Datetime\": \"Date\"}, inplace=True)\n",
            "        df[\"Date\"] = pd.to_datetime(df[\"Date\"]).dt.tz_localize(None)\n",
            "        df.set_index(\"Date\", inplace=True)\n",
            "        df = df[~df.index.duplicated(keep='first')].sort_index()\n",
            "        print(f\"Loaded {len(df)} daily bars for {symbol}.\")\n",
            "        return df\n",
            "    except Exception as e:\n",
            "        print(f\"Using synthetic generator for {symbol}: {e}\")\n",
            "        np.random.seed(42)\n",
            "        dates = pd.bdate_range(end=datetime.date.today(), periods=500)\n",
            "        ret = np.random.normal(0.0005, 0.018, len(dates))\n",
            "        price = 150.0 * np.exp(np.cumsum(ret))\n",
            "        df = pd.DataFrame({\n",
            "            \"Open\": price * 0.99, \"High\": price * 1.01, \"Low\": price * 0.985,\n",
            "            \"Close\": price, \"Volume\": np.random.randint(15000000, 80000000, len(dates))\n",
            "        }, index=dates)\n",
            "        return df\n",
            "\n",
            "# Load AAPL stock data\n",
            "df_raw = fetch_stock_dataset(\"AAPL\", period=\"2y\")\n",
            "df_raw.tail()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## ⚙️ Step 3: Technical Indicator Feature Engineering"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def add_indicators(df):\n",
            "    data = df.copy()\n",
            "    # Moving Averages\n",
            "    for w in [10, 20, 50, 200]:\n",
            "        data[f\"SMA_{w}\"] = data[\"Close\"].rolling(window=w, min_periods=1).mean()\n",
            "        data[f\"Price_to_SMA_{w}\"] = data[\"Close\"] / (data[f\"SMA_{w}\"] + 1e-8)\n",
            "    \n",
            "    data[\"EMA_12\"] = data[\"Close\"].ewm(span=12, adjust=False, min_periods=1).mean()\n",
            "    data[\"EMA_26\"] = data[\"Close\"].ewm(span=26, adjust=False, min_periods=1).mean()\n",
            "    data[\"MACD_Line\"] = data[\"EMA_12\"] - data[\"EMA_26\"]\n",
            "    data[\"MACD_Signal\"] = data[\"MACD_Line\"].ewm(span=9, adjust=False, min_periods=1).mean()\n",
            "    data[\"MACD_Hist\"] = data[\"MACD_Line\"] - data[\"MACD_Signal\"]\n",
            "    \n",
            "    # RSI 14\n",
            "    delta = data[\"Close\"].diff()\n",
            "    gain = (delta.where(delta > 0, 0)).rolling(window=14, min_periods=1).mean()\n",
            "    loss = (-delta.where(delta < 0, 0)).rolling(window=14, min_periods=1).mean()\n",
            "    rs = gain / (loss + 1e-8)\n",
            "    data[\"RSI_14\"] = 100 - (100 / (1 + rs))\n",
            "    \n",
            "    # Bollinger Bands\n",
            "    data[\"BB_Middle\"] = data[\"SMA_20\"]\n",
            "    std = data[\"Close\"].rolling(window=20, min_periods=1).std().fillna(0)\n",
            "    data[\"BB_Upper\"] = data[\"BB_Middle\"] + (2 * std)\n",
            "    data[\"BB_Lower\"] = data[\"BB_Middle\"] - (2 * std)\n",
            "    data[\"BB_Width\"] = (data[\"BB_Upper\"] - data[\"BB_Lower\"]) / (data[\"BB_Middle\"] + 1e-8)\n",
            "    data[\"BB_PctB\"] = (data[\"Close\"] - data[\"BB_Lower\"]) / (data[\"BB_Upper\"] - data[\"BB_Lower\"] + 1e-8)\n",
            "    \n",
            "    # ATR 14 & Stochastic Oscillator\n",
            "    tr = pd.concat([data[\"High\"] - data[\"Low\"], (data[\"High\"] - data[\"Close\"].shift(1)).abs(), (data[\"Low\"] - data[\"Close\"].shift(1)).abs()], axis=1).max(axis=1)\n",
            "    data[\"ATR_14\"] = tr.rolling(window=14, min_periods=1).mean()\n",
            "    data[\"Normalized_ATR\"] = data[\"ATR_14\"] / (data[\"Close\"] + 1e-8)\n",
            "    \n",
            "    low_14 = data[\"Low\"].rolling(window=14, min_periods=1).min()\n",
            "    high_14 = data[\"High\"].rolling(window=14, min_periods=1).max()\n",
            "    data[\"Stoch_K\"] = 100 * ((data[\"Close\"] - low_14) / (high_14 - low_14 + 1e-8))\n",
            "    data[\"Stoch_D\"] = data[\"Stoch_K\"].rolling(window=3, min_periods=1).mean()\n",
            "    \n",
            "    # Volume & Returns\n",
            "    data[\"Volume_SMA_20\"] = data[\"Volume\"].rolling(window=20, min_periods=1).mean()\n",
            "    data[\"Volume_Ratio\"] = data[\"Volume\"] / (data[\"Volume_SMA_20\"] + 1e-8)\n",
            "    data[\"Log_Return_1d\"] = np.log(data[\"Close\"] / data[\"Close\"].shift(1)).fillna(0)\n",
            "    data[\"Log_Return_5d\"] = np.log(data[\"Close\"] / data[\"Close\"].shift(5)).fillna(0)\n",
            "    data[\"Volatility_20\"] = data[\"Log_Return_1d\"].rolling(window=20, min_periods=1).std().fillna(0) * np.sqrt(252)\n",
            "    data[\"ROC_10\"] = (((data[\"Close\"] - data[\"Close\"].shift(10)) / (data[\"Close\"].shift(10) + 1e-8)) * 100).fillna(0)\n",
            "    \n",
            "    # Target Variable\n",
            "    data[\"Target_1d_Return\"] = (data[\"Close\"].shift(-1) - data[\"Close\"]) / data[\"Close\"]\n",
            "    return data\n",
            "\n",
            "df_feat = add_indicators(df_raw)\n",
            "print(f\"Computed {len(df_feat.columns)} technical indicators and target variables.\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## 📊 Step 4: Visualizing Stock Price & Technical Indicators"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(14, 10), sharex=True, gridspec_kw={'height_ratios': [3, 1, 1]})\n",
            "\n",
            "# 1. Price & Moving Averages\n",
            "ax1.plot(df_feat.index, df_feat[\"Close\"], label=\"Close Price\", color=\"#00f2fe\", linewidth=2)\n",
            "ax1.plot(df_feat.index, df_feat[\"SMA_20\"], label=\"SMA 20\", color=\"#38bdf8\", linestyle=\"--\")\n",
            "ax1.plot(df_feat.index, df_feat[\"SMA_50\"], label=\"SMA 50\", color=\"#fbbf24\", linestyle=\"--\")\n",
            "ax1.fill_between(df_feat.index, df_feat[\"BB_Upper\"], df_feat[\"BB_Lower\"], color=\"#8b5cf6\", alpha=0.15, label=\"Bollinger Bands\")\n",
            "ax1.set_title(\"AAPL Stock Price & Technical Indicator Bands\", fontsize=14, fontweight=\"bold\", color=\"#00f2fe\")\n",
            "ax1.set_ylabel(\"Price ($)\")\n",
            "ax1.legend(loc=\"upper left\")\n",
            "ax1.grid(True, alpha=0.2)\n",
            "\n",
            "# 2. RSI 14 Oscillator\n",
            "ax2.plot(df_feat.index, df_feat[\"RSI_14\"], color=\"#8b5cf6\", linewidth=1.5)\n",
            "ax2.axhline(70, color=\"#f43f5e\", linestyle=\"--\", alpha=0.7, label=\"Overbought (70)\")\n",
            "ax2.axhline(30, color=\"#10b981\", linestyle=\"--\", alpha=0.7, label=\"Oversold (30)\")\n",
            "ax2.set_ylabel(\"RSI (14)\")\n",
            "ax2.set_ylim(0, 100)\n",
            "ax2.legend(loc=\"upper left\")\n",
            "ax2.grid(True, alpha=0.2)\n",
            "\n",
            "# 3. MACD Histogram\n",
            "ax3.plot(df_feat.index, df_feat[\"MACD_Line\"], color=\"#38bdf8\", label=\"MACD Line\")\n",
            "ax3.plot(df_feat.index, df_feat[\"MACD_Signal\"], color=\"#f43f5e\", label=\"Signal\")\n",
            "ax3.bar(df_feat.index, df_feat[\"MACD_Hist\"], color=np.where(df_feat[\"MACD_Hist\"]>0, \"#10b981\", \"#f43f5e\"), alpha=0.5, label=\"Hist\")\n",
            "ax3.set_ylabel(\"MACD\")\n",
            "ax3.legend(loc=\"upper left\")\n",
            "ax3.grid(True, alpha=0.2)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## 🤖 Step 5: Dataset Split & Multi-Model Machine Learning Training"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "feature_cols = [\n",
            "    \"Price_to_SMA_10\", \"Price_to_SMA_20\", \"Price_to_SMA_50\", \"Price_to_SMA_200\",\n",
            "    \"MACD_Line\", \"MACD_Signal\", \"MACD_Hist\", \"RSI_14\", \"BB_Width\", \"BB_PctB\",\n",
            "    \"Normalized_ATR\", \"Stoch_K\", \"Stoch_D\", \"Volume_Ratio\", \"Log_Return_1d\",\n",
            "    \"Log_Return_5d\", \"Volatility_20\", \"ROC_10\"\n",
            "]\n",
            "\n",
            "# Clean dataset\n",
            "clean_df = df_feat.dropna(subset=feature_cols + [\"Target_1d_Return\"]).copy()\n",
            "\n",
            "# Chronological train/test split (80% Train, 20% Test)\n",
            "split_idx = int(len(clean_df) * 0.8)\n",
            "X_train = clean_df.iloc[:split_idx][feature_cols]\n",
            "X_test = clean_df.iloc[split_idx:][feature_cols]\n",
            "y_train = clean_df.iloc[:split_idx][\"Target_1d_Return\"]\n",
            "y_test = clean_df.iloc[split_idx:][\"Target_1d_Return\"]\n",
            "\n",
            "# Feature Scaling\n",
            "scaler = StandardScaler()\n",
            "X_train_scaled = scaler.fit_transform(X_train)\n",
            "X_test_scaled = scaler.transform(X_test)\n",
            "\n",
            "print(f\"Train set shape: {X_train.shape}, Test set shape: {X_test.shape}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Define and train model suite\n",
            "models = {\n",
            "    \"Random Forest\": RandomForestRegressor(n_estimators=150, max_depth=8, random_state=42),\n",
            "    \"Gradient Boosting\": GradientBoostingRegressor(n_estimators=120, learning_rate=0.03, max_depth=4, random_state=42),\n",
            "    \"Ridge Regression\": Ridge(alpha=2.0),\n",
            "    \"MLP Neural Net\": MLPRegressor(hidden_layer_sizes=(64, 32), max_iter=400, alpha=0.01, random_state=42)\n",
            "}\n",
            "\n",
            "print(\"Training ML Suite...\")\n",
            "results = {}\n",
            "test_predictions = {}\n",
            "\n",
            "for name, model in models.items():\n",
            "    model.fit(X_train_scaled, y_train)\n",
            "    preds = model.predict(X_test_scaled)\n",
            "    test_predictions[name] = preds\n",
            "    \n",
            "    rmse = float(np.sqrt(mean_squared_error(y_test, preds)))\n",
            "    mae = float(mean_absolute_error(y_test, preds))\n",
            "    r2 = float(r2_score(y_test, preds))\n",
            "    dir_acc = float(np.mean(np.sign(preds) == np.sign(y_test.values)) * 100)\n",
            "    \n",
            "    results[name] = {\"Directional Acc (%)\": round(dir_acc, 2), \"RMSE\": round(rmse, 6), \"MAE\": round(mae, 6), \"R2 Score\": round(r2, 4)}\n",
            "\n",
            "# Ensemble Model\n",
            "weights = [0.35, 0.35, 0.15, 0.15]\n",
            "ensemble_preds = sum(w * test_predictions[name] for w, name in zip(weights, models.keys()))\n",
            "test_predictions[\"Ensemble\"] = ensemble_preds\n",
            "\n",
            "ens_rmse = float(np.sqrt(mean_squared_error(y_test, ensemble_preds)))\n",
            "ens_mae = float(mean_absolute_error(y_test, ensemble_preds))\n",
            "ens_r2 = float(r2_score(y_test, ensemble_preds))\n",
            "ens_dir_acc = float(np.mean(np.sign(ensemble_preds) == np.sign(y_test.values)) * 100)\n",
            "results[\"⭐ Ensemble\"] = {\"Directional Acc (%)\": round(ens_dir_acc, 2), \"RMSE\": round(ens_rmse, 6), \"MAE\": round(ens_mae, 6), \"R2 Score\": round(ens_r2, 4)}\n",
            "\n",
            "# Display Results Table\n",
            "metrics_df = pd.DataFrame(results).T\n",
            "metrics_df"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## ⚡ Step 6: Feature Importance Analysis"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "rf_imp = models[\"Random Forest\"].feature_importances_\n",
            "gb_imp = models[\"Gradient Boosting\"].feature_importances_\n",
            "avg_imp = (rf_imp + gb_imp) / 2.0\n",
            "avg_imp = (avg_imp / np.sum(avg_imp)) * 100\n",
            "\n",
            "imp_df = pd.DataFrame({\"Feature\": feature_cols, \"Importance (%)\": avg_imp}).sort_values(by=\"Importance (%)\", ascending=False)\n",
            "\n",
            "plt.figure(figsize=(10, 6))\n",
            "sns.barplot(data=imp_df.head(10), x=\"Importance (%)\", y=\"Feature\", palette=\"mako\")\n",
            "plt.title(\"Top 10 Predictor Features (Tree-Based Importance)\", fontsize=14, fontweight=\"bold\", color=\"#00f2fe\")\n",
            "plt.grid(True, alpha=0.2)\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## 💼 Step 7: Algorithmic Trading Strategy Backtest"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Backtesting Engine Simulation\n",
            "test_df = clean_df.iloc[split_idx:].copy()\n",
            "initial_capital = 10000.0\n",
            "cash = initial_capital\n",
            "position = 0\n",
            "fee = 0.001\n",
            "portfolio_history = []\n",
            "bh_shares = initial_capital / test_df.iloc[0][\"Close\"]\n",
            "\n",
            "preds = test_predictions[\"Ensemble\"]\n",
            "for i in range(len(test_df)):\n",
            "    price = test_df.iloc[i][\"Close\"]\n",
            "    signal = preds[i]\n",
            "    \n",
            "    if signal > 0.0015 and position == 0:\n",
            "        position = (cash * (1 - fee)) / price\n",
            "        cash = 0\n",
            "    elif signal < -0.0015 and position > 0:\n",
            "        cash = position * price * (1 - fee)\n",
            "        position = 0\n",
            "        \n",
            "    port_val = cash + (position * price)\n",
            "    bh_val = bh_shares * price\n",
            "    portfolio_history.append({\"Date\": test_df.index[i], \"Strategy\": port_val, \"Buy_and_Hold\": bh_val})\n",
            "\n",
            "bt_df = pd.DataFrame(portfolio_history).set_index(\"Date\")\n",
            "strat_roi = ((bt_df[\"Strategy\"].iloc[-1] - initial_capital) / initial_capital) * 100\n",
            "bh_roi = ((bt_df[\"Buy_and_Hold\"].iloc[-1] - initial_capital) / initial_capital) * 100\n",
            "\n",
            "# Plot Equity Curve\n",
            "plt.figure(figsize=(12, 5))\n",
            "plt.plot(bt_df.index, bt_df[\"Strategy\"], label=f\"ML Strategy ROI: {strat_roi:.1f}%\", color=\"#10b981\", linewidth=2)\n",
            "plt.plot(bt_df.index, bt_df[\"Buy_and_Hold\"], label=f\"Buy & Hold ROI: {bh_roi:.1f}%\", color=\"#94a3b8\", linestyle=\"--\")\n",
            "plt.title(\"Algorithmic Trading Strategy Backtest vs Buy & Hold Benchmark\", fontsize=14, fontweight=\"bold\", color=\"#00f2fe\")\n",
            "plt.ylabel(\"Portfolio Value ($)\")\n",
            "plt.legend(loc=\"upper left\")\n",
            "plt.grid(True, alpha=0.2)\n",
            "plt.show()\n",
            "\n",
            "print(f\"🚀 Final Portfolio Value: ${bt_df['Strategy'].iloc[-1]:,.2f}\")\n",
            "print(f\"📈 Strategy ROI: {strat_roi:+.2f}% | Buy & Hold ROI: {bh_roi:+.2f}%\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## 🎯 Step 8: Multi-Day Future Horizon Forecasting"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Forecast next 30 days\n",
            "last_row = X_test_scaled[[-1]]\n",
            "expected_daily_return = float(sum(w * models[m].predict(last_row)[0] for w, m in zip(weights, models.keys())))\n",
            "curr_price = float(df_raw[\"Close\"].iloc[-1])\n",
            "vol = float(df_feat[\"Volatility_20\"].iloc[-1]) / np.sqrt(252)\n",
            "vol = max(vol, 0.008)\n",
            "\n",
            "future_days = []\n",
            "sim = curr_price\n",
            "for d in range(1, 31):\n",
            "    step_ret = expected_daily_return * (0.95 ** (d - 1))\n",
            "    sim *= (1 + step_ret)\n",
            "    std_bound = 1.645 * vol * np.sqrt(d) * sim\n",
            "    future_days.append({\"Day\": f\"Day {d}\", \"Predicted Price\": round(sim, 2), \"Lower 90%\": round(max(0.1, sim - std_bound), 2), \"Upper 90%\": round(sim + std_bound, 2)})\n",
            "\n",
            "forecast_df = pd.DataFrame(future_days)\n",
            "print(f\"Current Price: ${curr_price:.2f}\")\n",
            "print(forecast_df.iloc[[0, 4, 9, 14, 29]])"
        ]
    }
]

notebook_content = {
    "cells": cells,
    "metadata": {
        "language_info": {
            "name": "python",
            "version": "3.11"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open("stock_analysis_prediction.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=2)

print("Notebook stock_analysis_prediction.ipynb created successfully!")
